networks:
  dev:

volumes:
  pgdata:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - './ssl:/etc/nginx/ssl'
    depends_on:
      - backend
      - frontend
    networks:
      - dev

    

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - dev
    restart: always 


  frontend:
    build:
      context: ./frontend/robotic-main
    networks:
      - dev

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: robotick
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes: 
      - pgdata:/var/lib/postgresql/data
    networks:
      - dev